# Development environment values
app:
  environment: development

# Frontend configuration for development
frontend:
  replicaCount: 1
  image:
    repository: yaakovsm/pakalspot-frontend
    tag: dev-58bcefc
    pullPolicy: Always
  service:
    targetPort: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    VITE_HOST: "0.0.0.0"
    VITE_ALLOWED_HOSTS: "all"
    VITE_API_URL: "/api"
  envRuntime:
    GOOGLE_MAPS_API_KEY: "AIzaSyCwCjeTEmRel_nG1MGsC5sacEFGuipEs8k"

# Backend configuration for development
backend:
  replicaCount: 1
  image:
    repository: yaakovsm/pakalspot-backend
    tag: dev-58bcefc
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    DEBUG: "true"
    ENVIRONMENT: "development"

# Database configuration for development
database:
  statefulSet:
    replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  persistence:
    size: 10Gi

# Ingress configuration for development
ingress:
  enabled: true
  hosts:
    - host: pakalspot.local
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /media
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
