apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pakalspot
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
