apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pakalspot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yaakovsm/pakalspot-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              value: "postgresql://pakalspot_user:$(DB_PASSWORD)@postgres:5432/pakalspot_db"
            - name: JWT_EXPIRY
              value: "43200"
            - name: API_PREFIX
              value: "/api"
            - name: S3_BUCKET
              value: "pakalspot-photos"
            - name: S3_ENDPOINT
              value: "https://s3.amazonaws.com"
            - name: DEBUG
              value: "true"
            - name: ENVIRONMENT
              value: "development"
          envFrom:
            - secretRef:
                name: backend-secrets
            - secretRef:
                name: postgres-secrets

