apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: pakalspot
data:
  DB_URL: "postgresql://pakalspot_user:@postgres:5432/pakalspot_db"
  JWT_EXPIRY: "43200"
  API_PREFIX: "/api"
  S3_BUCKET: "pakalspot-photos"
  S3_ENDPOINT: "https://s3.amazonaws.com"
  DEBUG: "true"
  ENVIRONMENT: "development"

