apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed-job
  namespace: pakalspot
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-seed
          image: yaakovsm/pakalspot-backend:latest
          imagePullPolicy: Always
          command: ["python", "/app/app/db/seed.py"]
          env:
            - name: DB_URL
              value: "postgresql://pakalspot_user:$(DB_PASSWORD)@postgres:5432/pakalspot_db"
            - name: JWT_EXPIRY
              value: "43200"
            - name: API_PREFIX
              value: "/api"
            - name: S3_BUCKET
              value: "pakalspot-photos"
            - name: S3_ENDPOINT
              value: "https://s3.amazonaws.com"
            - name: DEBUG
              value: "true"
            - name: ENVIRONMENT
              value: "development"
          envFrom:
            - secretRef:
                name: backend-secrets
            - secretRef:
                name: postgres-secrets
