apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pakalspot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yaakovsm/pakalspot-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: frontend-config
          env:
            - name: VITE_HOST
              value: "0.0.0.0"
            - name: VITE_ALLOWED_HOSTS
              value: "all"

