apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pakalspot
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30080
      protocol: TCP
