apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pakalspot
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
