apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: pakalspot
type: Opaque
data:
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWhlcmUtY2hhbmdlLWluLXByb2R1Y3Rpb24=
  DB_PASSWORD: amNvZmZlZWJyZXc=
  S3_ACCESS_KEY: QUtJQVNVNTY2NVpTM1lYRFZGNFk=
  S3_SECRET_KEY: bC90YVlGbWZxcUNDbjVPNU9aVEFnVHg1R0x6RllKNENuNWFZc0lo

