services:
  db:
    image: postgis/postgis:15-3.3
    container_name: pakal-spot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pakalspot_user
      POSTGRES_PASSWORD: jcoffeebrew
      POSTGRES_DB: pakalspot_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - pakalspot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pakalspot_user -d pakalspot_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - DB_URL=postgresql://pakalspot_user:jcoffeebrew@db:5432/pakalspot_db
      - SECRET_KEY=${SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pakalspot-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000/api"
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
      MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    depends_on:
      - backend
    networks:
      - pakalspot-network

networks:
  pakalspot-network:
    driver: bridge

volumes:
  db_data:
