{{- if .Values.backend2.enabled }}
{{ include "noLatest" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-backend2
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend2
spec:
  replicas: {{ .Values.backend2.replicaCount }}
  selector:
    matchLabels:
      {{- include "pakalspot-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: backend2
  template:
    metadata:
      labels:
        {{- include "pakalspot-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: backend2
      {{- with .Values.backend2.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pakalspot-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend2
          image: {{ include "pakalspot-chart.image" (dict "root" . "service" "backend2") | quote }}
          imagePullPolicy: {{ include "pakalspot-chart.imagePullPolicy" (dict "root" . "service" "backend2") }}
          ports:
            - name: http
              containerPort: {{ .Values.backend2.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.backend2.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom: []
          {{- with .Values.backend2.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend2.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend2.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend2.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /app/media
      volumes:
        - name: media
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

