apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-backend-secrets
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.backend.SECRET_KEY | quote }}
  DB_PASSWORD: {{ .Values.secrets.backend.DB_PASSWORD | quote }}
  DB_URL: "postgresql://pakalspot_user:{{ .Values.secrets.backend.DB_PASSWORD }}@{{ include "pakalspot-chart.fullname" . }}-postgres:5432/pakalspot_db"
  S3_ACCESS_KEY: {{ .Values.backend.secrets.S3_ACCESS_KEY_ID | quote }}
  S3_SECRET_KEY: {{ .Values.backend.secrets.S3_SECRET_ACCESS_KEY | quote }}
  S3_ENDPOINT: {{ .Values.backend.secrets.S3_ENDPOINT | quote }}


