apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-db-secrets
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.database.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.database.POSTGRES_PASSWORD | quote }}

