apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-db-secrets
  labels:
    {{- include "pakalspot-chart.componentLabels" (dict "root" . "component" "database") | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.database.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.database.POSTGRES_PASSWORD | quote }}

