apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.appname }}
spec:
  selector:
    app: {{ .Values.database.appname }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
