apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pakalspot-frontend-env
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: pakalspot-frontend-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pakalspot/{{ .Values.app.environment }}/frontend
