apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pakalspot-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: pakalspot-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pakalspot/{{ .Values.app.environment }}/frontend
    - extract:
        key: /pakalspot/{{ .Values.app.environment }}/backend
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: ghcr-pull
    type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pakalspot/{{ .Values.app.environment }}/ghcr-pull

