apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
{{- if .Values.backend.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pakalspot-backend-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretstore
  target:
    name: pakalspot-backend-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pakalspot/backend
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pakalspot-frontend-env
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretstore
  target:
    name: pakalspot-frontend-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pakalspot/frontend
{{- end }}







