apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-frontend-env
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
data:
  env-config.js: |
    window.__ENV = {
      GOOGLE_MAPS_API_KEY: "{{ .Values.frontend.envRuntime.GOOGLE_MAPS_API_KEY }}"
    };
