apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: github-secrets
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-store
spec:
  provider:
    github:
      auth:
        secretRef:
          accessTokenSecretRef:
            name: github-secret-token
            key: token
      repository: {{ .Values.externalSecrets.github.repository }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
