apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-ing
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: pakalspot
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host | default "app.dev.pakalspot.com" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pakalspot-chart.fullname" . }}-frontend
                port:
                  number: 80
    - host: {{ .Values.ingress.apiHost | default "api.dev.pakalspot.com" }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "pakalspot-chart.fullname" . }}-backend
                port:
                  number: 8000
