{{- if and .Values.networkPolicy.enabled .Values.backend2.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-backend1-to-backend2
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchLabels:
      {{- include "pakalspot-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: backend2
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: NotIn
                values:
                  - backend1
{{- end }}
