apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: pakalspot-dev
data:
  default.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;

      # Inject env-config.js before </head>
      sub_filter_once off;
      sub_filter '</head>' '<script src="/env-config.js"></script></head>';
      sub_filter_types text/html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location = /env-config.js {
        try_files /env-config.js =404;
      }
    }
