apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-secrets
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-secret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: github-secrets
    kind: SecretStore
  target:
    name: {{ include "pakalspot-chart.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "pakalspot-chart.labels" . | nindent 10 }}
          app.kubernetes.io/component: secret
  data:
    {{- range $key, $value := .Values.externalSecrets.secrets }}
    - secretKey: {{ $key }}
      remoteRef: 
        key: {{ $value.remoteKey | default $key }}
    {{- end }}
