{{- if and .Values.podDisruptionBudget.enabled .Values.frontend.enabled }}
{{- if .Values.podDisruptionBudget.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-frontend
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if .Values.podDisruptionBudget.frontend.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.frontend.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.frontend.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pakalspot-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
{{- end }}

{{- if and .Values.podDisruptionBudget.enabled .Values.backend.enabled }}
{{- if .Values.podDisruptionBudget.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-backend
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if .Values.podDisruptionBudget.backend.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.backend.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.backend.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pakalspot-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
{{- end }}

