{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-quota
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
spec:
  hard:
    {{- range $key, $value := .Values.resourceQuota.hard }}
    {{- if $value }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
{{- end }}

