{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pakalspot-chart.serviceAccountName" . }}
  labels:
    {{- include "pakalspot-chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
