apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pakalspot-chart.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "pakalspot-chart.componentSelectorLabels" (dict "root" . "component" "backend") | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
