"""add_location_name_to_spots

Revision ID: 20250115_000002
Revises: 20250911_000001
Create Date: 2025-01-15 00:00:02.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250115_000002'
down_revision = '20250911_000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('location_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'location_name')
    # ### end Alembic commands ###


