"""add subtitle and how_to_get_there to spots

Revision ID: 20250120_000001
Revises: remove_region_column
Create Date: 2025-01-20 00:00:01.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250120_000001'
down_revision = 'remove_region_column'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('subtitle', sa.Text(), nullable=True))
    op.add_column('spots', sa.Column('how_to_get_there', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'how_to_get_there')
    op.drop_column('spots', 'subtitle')
    # ### end Alembic commands ###

